version: '3'
services:
    client:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        ports:
            - "3000:3000"
        stdin_open: true

    test:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./:/app
        stdin_open: true
        command: ["npm", "run", "test"]
   
